"""Platforms package.

Importing this package auto-imports every subpackage in `app/platforms/`
so that each platform's `register(...)` call runs and the shared shell
can discover what was built.

Do not edit this file unless you maintain the shell.
"""

from __future__ import annotations

import importlib
import logging
import pkgutil
from pathlib import Path

log = logging.getLogger("platforms")

_PACKAGE_DIR = Path(__file__).resolve().parent
_SKIP = {"registry"}


def _autoload_subpackages() -> None:
    for module_info in pkgutil.iter_modules([str(_PACKAGE_DIR)]):
        if not module_info.ispkg:
            continue
        name = module_info.name
        if name.startswith("_") or name in _SKIP:
            continue
        try:
            importlib.import_module(f"{__name__}.{name}")
            log.info("platforms: loaded %s", name)
        except Exception as exc:
            log.warning("platforms: skipped %s (%s)", name, exc)


_autoload_subpackages()
